.TH SECRET 1
.SH NAME
secret \- send & recieve files through encrypted ICMP packets
.SH SYNOPSIS
.B secret
\fB\-s\fR \fIHOST\fR \fB\-r\fR \fIFILE\fR [\fB\-v\fR]
.PP
.B secret 
\fB-l\fR [\fB\-v\fR]
.SH DESCRIPTION
.B secret
Program is divided into two parts -> \fBClient\fR and \fBServer\fR.
.PP
\fBClient\fR sends a file \fIFILE\fR to server specified on
IP/hostname \fIHOST\fR.
Client has no idea if Server recieved a file or not,
it simply sends the data.
Both arguments -r & -s are always required by client.
.PP
\fBServer\fR waits for a file to be send his way.
When whole file is recieved, save it to current dir.
If such file already exists(& is not empty), create new file with
prefix "isa_". This file is overwritten if necessary
(one backup system). Server runs until SIGINT (CTRL+C) or
error occurs. Therefore it's possible to send multiple files 
through one server run (not at the same time).
.SH OPTIONS
.TP
.BR -s " " \fIHOST\fR
IP/hostname where the file is to be send
.TP
.BR -r " " \fIFILE\fR
Path to a file to be send to server
.TP
.BR -l
Execute the program as server (this can't be combined
with -s or -r)
.TP
.BR -v
Enable verbose printing
.TP
.BR -h
Print out help message
.SH FILES
secret.h secret.c client.c server.c